services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.setup.conf:/etc/nginx/nginx.conf:ro
      - certbot_www:/var/www/certbot:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot

volumes:
  certbot_certs:
  certbot_www:
