PUT http://localhost:8080/v1/forms/X8YOGJYBdYEjCfUlHdsm HTTP/1.1
Content-Type: application/json
{
	
  "elements": [
    {
      "id": "0a487a10-7bd6-47cb-88f5-fe167c8916cd",
      "type": "header",
      "label": "Tomate final",
      "required": false
    },
    {
      "id": "912458cc-fde1-4a69-8856-0037e8118fde",
      "type": "text-input",
      "label": "teste editadaço",
      "required": false,
      "placeholder": "Enter text..."
    },
    {
      "id": "a89e5b0a-7de1-4b23-a30e-ee79a384e387",
      "type": "multiple-choice",
      "label": "Multiple Choice Question",
      "required": false,
      "options": [
        {
          "id": "cf4ad359-b527-4463-adef-aed24f5985e8",
          "label": "Alface",
          "value": "option_1",
          "isCorrect": true
        },
        {
          "id": "28a7cae5-4b2f-4636-a702-16c7fbf476e7",
          "label": "Tomate",
          "value": "option_2",
          "isCorrect": false
        },
        {
          "id": "1ed4a0de-f52d-4ac8-86ba-5449f7f32c04",
          "label": "Batata",
          "value": "option_3",
          "isCorrect": false
        }
      ]
    }
  ],
	"name":"Finalzaço"
}