/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PublicRouteImport } from './pages/_public'
import { Route as AuthenticatedRouteImport } from './pages/_authenticated'
import { Route as PublicIndexRouteImport } from './pages/_public/index'
import { Route as AuthenticatedAdminRouteImport } from './pages/_authenticated/_admin'
import { Route as PublicWelcomeIndexRouteImport } from './pages/_public/welcome/index'
import { Route as PublicVerifyEmailIndexRouteImport } from './pages/_public/verify-email/index'
import { Route as PublicRegisterIndexRouteImport } from './pages/_public/register/index'
import { Route as PublicPlansIndexRouteImport } from './pages/_public/plans/index'
import { Route as PublicLoginIndexRouteImport } from './pages/_public/login/index'
import { Route as PublicEmailsViewsIndexRouteImport } from './pages/_public/emails-views/index'
import { Route as AuthenticatedStartupIndexRouteImport } from './pages/_authenticated/startup/index'
import { Route as AuthenticatedInicioIndexRouteImport } from './pages/_authenticated/inicio/index'
import { Route as AuthenticatedVerifiedUsersIndexRouteImport } from './pages/_authenticated/_verified/users/index'
import { Route as PublicAuthGoogleCallbackIndexRouteImport } from './pages/_public/auth/google/callback/index'
import { Route as AuthenticatedVerifiedConfigurationProfilesIndexRouteImport } from './pages/_authenticated/_verified/configuration/profiles/index'
import { Route as AuthenticatedVerifiedConfigurationEnterpriseIndexRouteImport } from './pages/_authenticated/_verified/configuration/enterprise/index'
import { Route as AuthenticatedAdminAdminUsersIndexRouteImport } from './pages/_authenticated/_admin/admin/users/index'
import { Route as AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRouteImport } from './pages/_authenticated/_verified/configuration/enterprise/edit.$enterpriseId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicWelcomeIndexRoute = PublicWelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVerifyEmailIndexRoute = PublicVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterIndexRoute = PublicRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPlansIndexRoute = PublicPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEmailsViewsIndexRoute = PublicEmailsViewsIndexRouteImport.update({
  id: '/emails-views/',
  path: '/emails-views/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedStartupIndexRoute =
  AuthenticatedStartupIndexRouteImport.update({
    id: '/startup/',
    path: '/startup/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInicioIndexRoute =
  AuthenticatedInicioIndexRouteImport.update({
    id: '/inicio/',
    path: '/inicio/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVerifiedUsersIndexRoute =
  AuthenticatedVerifiedUsersIndexRouteImport.update({
    id: '/_verified/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicAuthGoogleCallbackIndexRoute =
  PublicAuthGoogleCallbackIndexRouteImport.update({
    id: '/auth/google/callback/',
    path: '/auth/google/callback/',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthenticatedVerifiedConfigurationProfilesIndexRoute =
  AuthenticatedVerifiedConfigurationProfilesIndexRouteImport.update({
    id: '/_verified/configuration/profiles/',
    path: '/configuration/profiles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVerifiedConfigurationEnterpriseIndexRoute =
  AuthenticatedVerifiedConfigurationEnterpriseIndexRouteImport.update({
    id: '/_verified/configuration/enterprise/',
    path: '/configuration/enterprise/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAdminUsersIndexRoute =
  AuthenticatedAdminAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRoute =
  AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRouteImport.update(
    {
      id: '/_verified/configuration/enterprise/edit/$enterpriseId',
      path: '/configuration/enterprise/edit/$enterpriseId',
      getParentRoute: () => AuthenticatedRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/inicio/': typeof AuthenticatedInicioIndexRoute
  '/startup/': typeof AuthenticatedStartupIndexRoute
  '/emails-views/': typeof PublicEmailsViewsIndexRoute
  '/login/': typeof PublicLoginIndexRoute
  '/plans/': typeof PublicPlansIndexRoute
  '/register/': typeof PublicRegisterIndexRoute
  '/verify-email/': typeof PublicVerifyEmailIndexRoute
  '/welcome/': typeof PublicWelcomeIndexRoute
  '/users/': typeof AuthenticatedVerifiedUsersIndexRoute
  '/admin/users/': typeof AuthenticatedAdminAdminUsersIndexRoute
  '/configuration/enterprise/': typeof AuthenticatedVerifiedConfigurationEnterpriseIndexRoute
  '/configuration/profiles/': typeof AuthenticatedVerifiedConfigurationProfilesIndexRoute
  '/auth/google/callback/': typeof PublicAuthGoogleCallbackIndexRoute
  '/configuration/enterprise/edit/$enterpriseId': typeof AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/inicio': typeof AuthenticatedInicioIndexRoute
  '/startup': typeof AuthenticatedStartupIndexRoute
  '/emails-views': typeof PublicEmailsViewsIndexRoute
  '/login': typeof PublicLoginIndexRoute
  '/plans': typeof PublicPlansIndexRoute
  '/register': typeof PublicRegisterIndexRoute
  '/verify-email': typeof PublicVerifyEmailIndexRoute
  '/welcome': typeof PublicWelcomeIndexRoute
  '/users': typeof AuthenticatedVerifiedUsersIndexRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersIndexRoute
  '/configuration/enterprise': typeof AuthenticatedVerifiedConfigurationEnterpriseIndexRoute
  '/configuration/profiles': typeof AuthenticatedVerifiedConfigurationProfilesIndexRoute
  '/auth/google/callback': typeof PublicAuthGoogleCallbackIndexRoute
  '/configuration/enterprise/edit/$enterpriseId': typeof AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/inicio/': typeof AuthenticatedInicioIndexRoute
  '/_authenticated/startup/': typeof AuthenticatedStartupIndexRoute
  '/_public/emails-views/': typeof PublicEmailsViewsIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
  '/_public/plans/': typeof PublicPlansIndexRoute
  '/_public/register/': typeof PublicRegisterIndexRoute
  '/_public/verify-email/': typeof PublicVerifyEmailIndexRoute
  '/_public/welcome/': typeof PublicWelcomeIndexRoute
  '/_authenticated/_verified/users/': typeof AuthenticatedVerifiedUsersIndexRoute
  '/_authenticated/_admin/admin/users/': typeof AuthenticatedAdminAdminUsersIndexRoute
  '/_authenticated/_verified/configuration/enterprise/': typeof AuthenticatedVerifiedConfigurationEnterpriseIndexRoute
  '/_authenticated/_verified/configuration/profiles/': typeof AuthenticatedVerifiedConfigurationProfilesIndexRoute
  '/_public/auth/google/callback/': typeof PublicAuthGoogleCallbackIndexRoute
  '/_authenticated/_verified/configuration/enterprise/edit/$enterpriseId': typeof AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inicio/'
    | '/startup/'
    | '/emails-views/'
    | '/login/'
    | '/plans/'
    | '/register/'
    | '/verify-email/'
    | '/welcome/'
    | '/users/'
    | '/admin/users/'
    | '/configuration/enterprise/'
    | '/configuration/profiles/'
    | '/auth/google/callback/'
    | '/configuration/enterprise/edit/$enterpriseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inicio'
    | '/startup'
    | '/emails-views'
    | '/login'
    | '/plans'
    | '/register'
    | '/verify-email'
    | '/welcome'
    | '/users'
    | '/admin/users'
    | '/configuration/enterprise'
    | '/configuration/profiles'
    | '/auth/google/callback'
    | '/configuration/enterprise/edit/$enterpriseId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_admin'
    | '/_public/'
    | '/_authenticated/inicio/'
    | '/_authenticated/startup/'
    | '/_public/emails-views/'
    | '/_public/login/'
    | '/_public/plans/'
    | '/_public/register/'
    | '/_public/verify-email/'
    | '/_public/welcome/'
    | '/_authenticated/_verified/users/'
    | '/_authenticated/_admin/admin/users/'
    | '/_authenticated/_verified/configuration/enterprise/'
    | '/_authenticated/_verified/configuration/profiles/'
    | '/_public/auth/google/callback/'
    | '/_authenticated/_verified/configuration/enterprise/edit/$enterpriseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/welcome/': {
      id: '/_public/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof PublicWelcomeIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/verify-email/': {
      id: '/_public/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof PublicVerifyEmailIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register/': {
      id: '/_public/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof PublicRegisterIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/plans/': {
      id: '/_public/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof PublicPlansIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/emails-views/': {
      id: '/_public/emails-views/'
      path: '/emails-views'
      fullPath: '/emails-views/'
      preLoaderRoute: typeof PublicEmailsViewsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/startup/': {
      id: '/_authenticated/startup/'
      path: '/startup'
      fullPath: '/startup/'
      preLoaderRoute: typeof AuthenticatedStartupIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inicio/': {
      id: '/_authenticated/inicio/'
      path: '/inicio'
      fullPath: '/inicio/'
      preLoaderRoute: typeof AuthenticatedInicioIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_verified/users/': {
      id: '/_authenticated/_verified/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedVerifiedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/auth/google/callback/': {
      id: '/_public/auth/google/callback/'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback/'
      preLoaderRoute: typeof PublicAuthGoogleCallbackIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_verified/configuration/profiles/': {
      id: '/_authenticated/_verified/configuration/profiles/'
      path: '/configuration/profiles'
      fullPath: '/configuration/profiles/'
      preLoaderRoute: typeof AuthenticatedVerifiedConfigurationProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_verified/configuration/enterprise/': {
      id: '/_authenticated/_verified/configuration/enterprise/'
      path: '/configuration/enterprise'
      fullPath: '/configuration/enterprise/'
      preLoaderRoute: typeof AuthenticatedVerifiedConfigurationEnterpriseIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/admin/users/': {
      id: '/_authenticated/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_verified/configuration/enterprise/edit/$enterpriseId': {
      id: '/_authenticated/_verified/configuration/enterprise/edit/$enterpriseId'
      path: '/configuration/enterprise/edit/$enterpriseId'
      fullPath: '/configuration/enterprise/edit/$enterpriseId'
      preLoaderRoute: typeof AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminUsersIndexRoute: typeof AuthenticatedAdminAdminUsersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminUsersIndexRoute:
    AuthenticatedAdminAdminUsersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedInicioIndexRoute: typeof AuthenticatedInicioIndexRoute
  AuthenticatedStartupIndexRoute: typeof AuthenticatedStartupIndexRoute
  AuthenticatedVerifiedUsersIndexRoute: typeof AuthenticatedVerifiedUsersIndexRoute
  AuthenticatedVerifiedConfigurationEnterpriseIndexRoute: typeof AuthenticatedVerifiedConfigurationEnterpriseIndexRoute
  AuthenticatedVerifiedConfigurationProfilesIndexRoute: typeof AuthenticatedVerifiedConfigurationProfilesIndexRoute
  AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRoute: typeof AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedInicioIndexRoute: AuthenticatedInicioIndexRoute,
  AuthenticatedStartupIndexRoute: AuthenticatedStartupIndexRoute,
  AuthenticatedVerifiedUsersIndexRoute: AuthenticatedVerifiedUsersIndexRoute,
  AuthenticatedVerifiedConfigurationEnterpriseIndexRoute:
    AuthenticatedVerifiedConfigurationEnterpriseIndexRoute,
  AuthenticatedVerifiedConfigurationProfilesIndexRoute:
    AuthenticatedVerifiedConfigurationProfilesIndexRoute,
  AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRoute:
    AuthenticatedVerifiedConfigurationEnterpriseEditEnterpriseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicEmailsViewsIndexRoute: typeof PublicEmailsViewsIndexRoute
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
  PublicPlansIndexRoute: typeof PublicPlansIndexRoute
  PublicRegisterIndexRoute: typeof PublicRegisterIndexRoute
  PublicVerifyEmailIndexRoute: typeof PublicVerifyEmailIndexRoute
  PublicWelcomeIndexRoute: typeof PublicWelcomeIndexRoute
  PublicAuthGoogleCallbackIndexRoute: typeof PublicAuthGoogleCallbackIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicEmailsViewsIndexRoute: PublicEmailsViewsIndexRoute,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
  PublicPlansIndexRoute: PublicPlansIndexRoute,
  PublicRegisterIndexRoute: PublicRegisterIndexRoute,
  PublicVerifyEmailIndexRoute: PublicVerifyEmailIndexRoute,
  PublicWelcomeIndexRoute: PublicWelcomeIndexRoute,
  PublicAuthGoogleCallbackIndexRoute: PublicAuthGoogleCallbackIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
