export const REPOSITORY_TOKENS_TENANT = {
  ENTERPRISE_REPOSITORY: Symbol('ENTERPRISE_REPOSITORY'),
  ENTERPRISE_MEMBER_REPOSITORY: Symbol(
    'ENTERPRISE_MEMBER_REPOSITORY',
  ),
  PROFILE_REPOSITORY: Symbol('PROFILE_REPOSITORY'),
  CUSTOMER_REPOSITORY: Symbol('CUSTOMER_REPOSITORY'),
  FILE_REPOSITORY: Symbol('FILE_REPOSITORY'),
} as const;

export type RepositoryTokens =
  (typeof REPOSITORY_TOKENS_TENANT)[keyof typeof REPOSITORY_TOKENS_TENANT];
